#!/bin/bash
#
# Show only the latest Arch news headline.
# Useful e.g. for 'kalu' news.conf.

Main()
{
    local info=$(mktemp)
    wget -q -T 10 -O $info https://www.archlinux.org/ && \
        { grep 'title="View full article:' $info | sed -e 's|&gt;|>|g' -e 's|^.*">[ ]*||' -e 's|</a>$||' | head -n 1 ; }
    rm -f $info
}

Main "$@"
