#!/bin/bash
#
# Identify machine's CPU type (e.g. GenuineIntel).

# outputs "GenuineIntel" or something else (I don't have AMD machines...)

# lscpu | grep "^Vendor ID:" | awk '{print $3}'

grep -w "^vendor_id" /proc/cpuinfo | head -n 1 | awk '{print $3}'
