#!/bin/bash

REFLECTOR_COUNTRIES="$(reflector --list-countries)"

CodeToCountry() {  # convert country code to country name
    local code="$1"
    echo "$REFLECTOR_COUNTRIES" | grep -w "$code" | sed 's|^\(.*[a-z]\)[ ]*[A-Z][A-Z].*$|\1|'
}

CCCheck() {   # check validity of country code
    case "$1" in
        [A-Z][A-Z]) test -n "$(CodeToCountry "$1")" && return 0 ;;
    esac
    return 1  # fail
}

GetYourCountryCode() {
    local IP code

    IP="$(dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com | tr -d '"')"  # ipv4 address
    code="$(geoiplookup "$IP" | sed 's|^.*: \([A-Z][A-Z]\),.*$|\1|')"
    CCCheck "$code" && {
        echo "$code" ; return
    }
    code="$(whois "$IP" | grep ^country: | awk '{print $NF}')"
    CCCheck "$code" && {
        echo "$code" ; return
    }

    IP="$(dig -6 TXT +short o-o.myaddr.l.google.com @ns1.google.com | tr -d '"')"  # ipv6 address
    code="$(geoiplookup6 "$IP" | sed 's|^.*: \([A-Z][A-Z]\),.*$|\1|')"
    CCCheck "$code" && {
        echo "$code" ; return
    }
    code="$(whois "$IP" | grep ^country: | awk '{print $NF}')"
    CCCheck "$code" && {
        echo "$code" ; return
    }

    # net services failed, use local variables, but may be wrong
    code="$(locale | grep ^LC_TIME | cut -d '"' -f 2 | sed 's|^.*_\([A-Z][A-Z]\)\..*$|\1|')"
    CCCheck "$code" && {
        echo "$code" ; return
    }
}

ArgsYesNo() {
    echo "yes" ; return  # comment out this line to be less verbose

    local searched="$1"
    shift
    for xx in "$@" ; do
        test "$xx" = "$searched" && { echo "yes" ; return ; }
    done
    echo "no"
}

Main() {
    local verbose=$(ArgsYesNo -v "$@")
    local showlist=$(ArgsYesNo -l "$@")

    test "$verbose" = "yes" && echo "Find your country ..." >&2

    local cc="$(GetYourCountryCode)"
    local countrynames
    local countrycodes
    local xx ix=0
    local result countries
    local command tmpfile=$(mktemp)
    local ml=/etc/pacman.d/mirrorlist

    readarray -t countrynames <<< "$(echo "$REFLECTOR_COUNTRIES" | sed 's|^\(.*[a-z]\)[ ]*[A-Z][A-Z].*$|\1|')"
    readarray -t countrycodes <<< "$(echo "$REFLECTOR_COUNTRIES" | awk '{print $(NF-1)}')"

    countries=$(for xx in "${countrycodes[@]}" ; do
                    case "$xx" in
                        "$cc") echo "true"  ;;
                        *)     echo "false" ;;
                    esac
                    echo "${countrynames[$ix]}"
                    ((ix++))
                done
             )
    readarray -t result <<< \
              $(echo "$countries" | \
                    yad --height=600 --width=300 --list --checklist --title="Selecting pacman mirrors" \
                        --text="Select mirror countries:\n- closest locations recommended\n- one or more countries" \
                        --column="Select" --column="Country name" \
                    | cut -d '|' -f 2
              )
    test -n "$result" || return

    command=(reflector)
    test -r /etc/reflector-auto.conf && command+=($(cat /etc/reflector-auto.conf | grep -P -v "^[ \t]*#|^$"))
    command+=(-a2 -phttps -f10 --sort rate --save $tmpfile)
    for xx in "${result[@]}" ; do
        command+=(-c "$xx")
    done

    "${command[@]}"

    test "$showlist" = "yes" && cat $tmpfile >&2

    test "$verbose" = "yes" && echo "Saving mirrorlist to /etc/pacman.d ..." >&2
    pkexec bash -c "cp $ml $ml.bak && cp $tmpfile $ml"
    rm -f $tmpfile
}

Main "$@"
